name: github pages

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.76.5'
          extended: true
      - name: Build
        run: hugo --minify --gc --destination ./public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.PUBLISH_GIULIOV_GITHUB_IO }}
          external_repository: giuliov/giuliov.github.io
          publish_branch: master
          publish_dir: ./public
